### ISSUE TITLE
SIGSEV after 4 or 8 threads

### ISSUE THREAD

**Issue by mader102** [KjellKod/g3log#131]
Hi KjellKod,

I am trying to create a benchmark to compare few loggers:
Log4j2, logback, glog, g3log, reckless and spdlog.

I found out, that reckless and spdlog are over the top and spdlog, but I also see error messages while logging for reckless and g3log.

What I am doing is, to create a JNI class to use C++ logger in my Java written benchmark.
It works well for spdlog and glog and also reckless is not that bad, but g3log dies after going to 4+ threads.

This is the error message I see the most:
***** FATAL SIGNAL RECEIVED *******
"Received fatal signal: SIGSEGV(11)     PID: 5662

***** SIGNAL SIGSEGV(11)

******* STACKDUMP *******
        stack dump [1]  lib/libg3logger.so+0x12af7 [0x7f50a7bafaf7]
        stack dump [2]  /lib/x86_64-linux-gnu/libpthread.so.0+0xf8d0 [0x7f50ccfc48d0]
        stack dump [3]  /home/benchmark/jdk1.8.0_112/jre/lib/amd64/server/libjvm.so+0x9251e4 [0x7f50cc1231e4]
        stack dump [4]  /home/benchmark/jdk1.8.0_112/jre/lib/amd64/server/libjvm.so+0x91c2b3 [0x7f50cc11a2b3]
        stack dump [5]  /home/benchmark/jdk1.8.0_112/jre/lib/amd64/server/libjvm.so+0xa755f3 [0x7f50cc2735f3]
        stack dump [6]  /home/benchmark/jdk1.8.0_112/jre/lib/amd64/server/libjvm.so+0xa7573c [0x7f50cc27373c]
        stack dump [7]  /home/benchmark/jdk1.8.0_112/jre/lib/amd64/server/libjvm.so+0x926138 [0x7f50cc124138]
        stack dump [8]  /lib/x86_64-linux-gnu/libpthread.so.0+0x80a4 [0x7f50ccfbd0a4]
        stack dump [9]  /lib/x86_64-linux-gnu/libc.so.6clone+0x6d [0x7f50cc8d887d]

Exiting after fatal event  (FATAL_SIGNAL). Fatal type:  SIGSEGV
Log content flushed sucessfully to sink

"
g3log g3FileSink shutdown at: 14:45:48 755467
Log file at: [logs/libg3log.g3log.20161112-144457.log]

exitWithDefaultSignalHandler:238. Exiting due to FATAL_SIGNAL, 11

./run.sh: line 19:  5662 Segmentation fault      $script $logger $benchmark $thread

Essentially this is how I create a logger object, maybe there is something wrong.
G3log was promising, but this SIGSEV makes it impossible to use the results.

JNIEXPORT void JNICALL Java_framework_JNI_G3logJNI_init(JNIEnv *env, jobject thisObj, jstring _location)
{
	static std::unique_ptr<g3::LogWorker> gMainLogger = g3::LogWorker::createLogWorker();
	auto defaultHandler = gMainLogger->addSink(std2::make_unique<g3::FileSink>("libg3log", location), 
	  &g3::FileSink::fileWrite);
	  g3::initializeLogging(gMainLogger.get());
}

it is an adaption of https://github.com/KjellKod/g3log/issues/35#issuecomment-128583349

With kind regards
mader102

**Comment by KjellKod** [comment]
Sorry, I have no experience in `JNIEXPORT. It seems you are trying to use the logger without adhering to the `RAII` break-down. Maybe this issue and it's resolution is more helpful to you? https://github.com/KjellKod/g3log/issues/88

**Comment by KjellKod** [comment]
FYI:  Nanolog (https://github.com/Iyengar111/NanoLog) and spdlog are top notch super fast logging libraries.  If speed is the one criterion you are after I would suggest you look at Nanolog: https://github.com/Iyengar111/NanoLog    (with the g4log changes in 2017 g3log might be a contender too). 

If you want "crash safety" and short "worst case latency" spikes then g3log could be your candidate.

**Comment by KjellKod** [comment]
I see no action on g3log regarding this. Feel free to reach out on my personal email if you need advice on how to proceed.

**Comment by krishnadasari610** [comment]
Hi All
I am facing the below issue while running my application inside the container, can anyone please guide me on how to fix this error. I am unable to run my application (edited) 
admin@9e339bb1afb3:~/home/admin/apps/MainApp$ ./MainApp
2019/12/20 10:26:16.653      INFO  9e339bb1afb3, 0, MainApp, 22, v1.0.0.7703 b01a5f655cb7f1fcae8362d9318949257559e3f0
2019/12/20 10:26:16.653      INFO  9e339bb1afb3, 0, MainApp, 24, HOME_PATH is found, directory :~/home/admin/
Valid License loaded from file.
2019/12/20 10:26:16.653      INFO  9e339bb1afb3, 0, MainApp, 1, Enabled Features: 0xFFFFF
2019/12/20 10:26:16.653      CRITICAL     9e339bb1afb3, 2, AppController, 2022, Failed to parse Variable key: Site
2019/12/20 10:26:16.653      CRITICAL     9e339bb1afb3, 2, AppController, 2022, Failed to parse Variable key: SiteAddress
2019/12/20 10:26:16.653      CRITICAL     9e339bb1afb3, 2, AppController, 2022, Failed to parse Variable key: StationSerialNumber
2019/12/20 10:26:16.653      CRITICAL     9e339bb1afb3, 2, AppController, 2022, Failed to parse Variable key: SoftwareRelease
2019/12/20 10:26:16.653      CRITICAL     9e339bb1afb3, 2, AppController, 2022, Failed to parse Variable key: SoftwareVersion
2019/12/20 10:26:16.653      CRITICAL     9e339bb1afb3, 2, AppController, 2024, Failed to parse station information.
2019/12/20 10:26:16.653      INFO  9e339bb1afb3, 2, AppController, 2049, AppFeatureFactory created.
2019/12/20 10:26:16.653      CRITICAL     9e339bb1afb3, 2, AppController, 2060, AppConfig map is empty.
2019/12/20 10:26:16.653      DEBUG          9e339bb1afb3, 0, MainApp, 2, Creating AppFeature objects.
2019/12/20 10:26:16.653
***** FATAL SIGNAL RECEIVED *******
Received fatal signal: SIGSEGV(11) PID: 27
***** SIGNAL SIGSEGV(11)
*******         STACKDUMP *******
           stack dump [1] :~/home/admin/apps/MainApp /libLogger.so+0x5b4ce [0x7f1d1add94ce]
           stack dump [2] /lib/x86_64-linux-gnu/libpthread.so.0+0x12890 [0x7f1d1a232890]
           stack dump [3:~/home/admin/apps/MainApp /libAppController.so : app_controller::AppController::GetAppFeaturesList() const+0x11 [0x7f1d1b2686c1]
           stack dump [4] ./MainApp+0x60015 [0x55b280e4e015]
           stack dump [5] /lib/x86_64-linux-gnu/libc.so.6__libc_start_main+0xe7 [0x7f1d19e50b97]
           stack dump [6] ./MainApp+0x6261a [0x55b280e5061a]
Exiting after fatal event (FATAL_SIGNAL). Fatal type: SIGSEGV
Log content flushed sucessfully to sink
2019/12/20 10:26:16.653      DEBUG          Received fatal signal: SIGSEGV(11) PID: 27
***** SIGNAL SIGSEGV(11)
*******         STACKDUMP *******
           stack dump [1] :~/home/admin/apps/MainApp /libLogger.so+0x5b4ce [0x7f1d1add94ce]
           stack dump [2] /lib/x86_64-linux-gnu/libpthread.so.0+0x12890 [0x7f1d1a232890]
           stack dump [3] :~/home/admin/apps/MainApp /libAppController.so : app_controller::AppController::GetAppFeaturesList() const+0x11 [0x7f1d1b2686c1]
           stack dump [4] ./MainApp+0x60015 [0x55b280e4e015]
           stack dump [5] /lib/x86_64-linux-gnu/libc.so.6__libc_start_main+0xe7 [0x7f1d19e50b97]
           stack dump [6] ./MainApp+0x6261a [0x55b280e5061a]
Exiting after fatal event (FATAL_SIGNAL). Fatal type: SIGSEGV
Log content flushed sucessfully to sink
exitWithDefaultSignalHandler:296. Exiting due to FATAL_SIGNAL, 11  
Segmentation fault (core dumped)
![IMG_20191220_155123](https://user-images.githubusercontent.com/19946280/71252971-7d022280-234c-11ea-9921-dbc952ce842a.jpg)

**Comment by KjellKod** [comment]
Thanks for coding it. Looks like memory corruption in your code
