### ISSUE TITLE
Scalability

### ISSUE THREAD

**Issue by Code-ReaQtor** [KjellKod/g3log#148]
How does this library respond to scalability? One example is multi-process logging (Possibly, multiple processes writing on the same file).

Thanks!

**Comment by KjellKod** [comment]
You mean something like this? https://github.com/d-led/zmqlogger

Apart from that logger extension of g3log I am not aware of another process to process logging utilization of g3log.

i have never seen the need for it either. To me, the most common need is that each process logs to its own file. I have discussed having the local logging as well as pushing the log to one log repository. I have not attempted this yet but if I did it would probably follow this: 
- using g3sinks file rotation sink logging instead of the default for the local logging
- using a new sink, custom made, for pushing the log data with added process information (name of process etc) to the remote receiver which may or may not be on the same server. I.e it should handle process to process as well as process to cloud
- ZMQ is a likely technology for the log traffic but there are other technologies about there that might be more suitable depending on the needs of the receiving side.

At the moment I have not looked into implementing this but I'm fairly sure it will be approached during 2017

**Comment by Code-ReaQtor** [comment]
Checked [zmqlogger](https://github.com/d-led/zmqlogger) but the description says it uses g2log as a backend. Will it be compatible with g3log?

**Comment by KjellKod** [comment]
I haven't tried zmqlogger myself but API wise g2log and g3log are similar. G3log has more functionality

**Comment by Code-ReaQtor** [comment]
Thanks @KjellKod
