### ISSUE TITLE
g3log usage in multiple instances of a class with different sinks

### ISSUE THREAD

**Issue by mschollerer** [KjellKod/g3log#153]
First of all g3log is greatly suitable for our realtime project, but in the way we would like to use it, we are faced with some problems.

Preferred usage would look like:
- every instance of ExampleClass gets its own logger/filesink/logfile
- every instance of ExampleClass shuts down its own logger/filesink/logfile

```
std::unique_ptr<g3::LogWorker> LogWorker = {g3::LogWorker::createLogWorker()};
std::unique_ptr<g3::FileSinkHandle> FileSink;

ExampleClass::ExampleClass(const string InstanceName)
{
  LogWorker->addSink(std2::make_unique<g3::FileSink>("ExampleClass", "log/", InstanceName), g3::FileSink::fileWrite);

  g3::initializeLogging(LogWorker.get());

  LOGF(DEBUG, "ExcampleClass instance %s created", InstanceName.c_str ());
}

ExampleClass::~ExampleClass()
{
  // not really needed, just to show the intention of usage, would like to shutdown filesink here
  g3::internal::shutDownLoggingForActiveOnly(LogWorker.get());
}
```
I'm faced with three main problems:
- initializeLogging of following instances failes (multiple init), but would be able to overcome by using isLoggingInitialized.
- all instances log in first file 
- the LogWorker is completely shut down after one instance is shut down. All other instances are not able to log anymore from this point on.

Is there a way to use g3log in the manner I would like to?

Best Regards
Michael

**Comment by KjellKod** [comment]
You can have multiple instances of g3log log worker for sure (ref the unit tests) but you cannot instanciate more than one.

This is by design. 

What is the problem you are trying to solve here? To have x classes only showing up in one log file? If so you can look into filtering instead. Please see the g3sinks logging sinks (rotate and filter sink) you should be able to easily adjust it to your purposes or just write your own 

I.e with some sink creation of your own you can have one sink can take entries from multiple sources but pushing the entries to different log files

Or you can have multiple sinks each filtering out all entries except the ones from the approved sources and then pushing the approved entries to one file

Just a few suggestions. G3log is built to be sink-extendible

**Comment by mschollerer** [comment]
Thank you for your quick reply. 

Please have a look at the following source to clarify my idea:

`LogWorker->addSink(std2::make_unique<g3::FileSink>("ExampleClass", "log/", InstanceName), g3::FileSink::fileWrite);
`
I would like achieve that each instance of ExampleClass logs to its own logfile using a global g3log instance. I thought this could be achieved by using different sinks per instance, but all instances log to the same (first) file.

I hope my approach is more understandable now.

I'm still not quite sure how to achieve this behaviour using g3log, perhaps you could give me a hint!

**Comment by KjellKod** [comment]
Hi

Yup the idea is perfectly clear. One way to achieve this is to use a custom sink that looks at the incoming log messages and from the information there determines what log file it should go to.

Function (with class I believe), filename and line number is already available. Currently there is no object information passed on with the log message so the LOG(....) calls would have to be extended.

I believe I understand the functionality you are striving for. Currently the roadmap for g3log is not aligned in that direction. 

The good news is that g3log is not only public source but also public domain. Feel free to fork the repository and make the necessary changes. If you later think it's good enough to warrant a change of the public g3log then a pull request to g3log will be given attention and be reviewed and discussed. Regardless of g3log contribution you would still have your logger the way you want it 

Thanks
Kjell

**Comment by KjellKod** [comment]
FYI, another approach which I've seen in action could work in the following manner. 

Each object that needs their own separate logging holds their own logging sink wrapped in a `concurrent` object. Ref: https://github.com/KjellKod/concurrent/blob/master/src/concurrent.hpp

You can have a new logging macro (ex `LOGTO(LEVEL, sink_instance) << "stuff";` where LEVEL would be one of INFO, WARNING etc) This new logging macro would expand the input just like the current logging macros are but it would push the resulting `LogMessage` onto the sink_instance. 

The `concurrent<Sink>` would then utilize the  call `concurrent::fire` to send asynchronously the logging message to the logging sink. I.e. essentially you get the g3log async behavior without much of the g3log framework. 


I.e. pseudo code 
```
   MyClass {
        shared_ptr<concurrent<MySink>> mSink;
      MyClass(string name)  :   mSink /* instantiation*/  {}

     void Foo()  {
         // stuff
         LOGTO(INFO, mSink) << "This log message will be on a log file specific for this object";  
         }
  };

   // elsewhere
   LOGTO(level, instance) \
    /* deal with log message creation*/ \
   instance.fire(&MySink::saveToLog, std::string{message + "\n"});
```

**Comment by gaviriar** [comment]
I there, I have a quick question about this topic. I would like to clarify your last suggestion above. In this case where each object holds their own logging sink, you mean that we do not use the `LogWorker` at all? 

But rather utilize the Sink's functionality to just do the writing to the file?

If this is the case, what would be the main caveat's to watch out for, considering that we may be missing out some of the robust logging functionality offered by the LogWorker and the rest of the framework?

**Comment by KjellKod** [comment]
At that point you are only Using the ”write to disk” functionality i.e the following is missing
- handling of logging levels
- crash capture and dump of stack
- async log writing (you can get that easily if you wrap it in my concurrent wrapper (check my repos)

**Comment by gaviriar** [comment]
Hi @KjellKod, ok thanks for the clarification that makes sense. 

Sure, I will check out your repos and see what I can reuse.

Thanks again

**Comment by TelephonyMan** [comment]
I ran into the same issue. I am planning to switch from the home grown logger into g3log because of crash capture and stack dump feature. I have many applications running on freeswitch platform. Each application is a library file (.dll or .so) loaded dynamically. In Windows it is very easy to have separate log file for each module, even though they are part of a single process. In Linux, it doesn't work. The moment I load the second application, it crashes freeswitch because of multiple initialization. I don't see a workaround to avoid global sink, without losing key features. Looks like I have to consider using a common log file for the Linux version.

**Comment by KjellKod** [comment]
Not sure what you are asking @TelephonyMan

Is G3log crashing your application due to multiple instantiation? Or is it your own logger that is causing this? 

G3log must only be initialized once. 

For non-global, logging I would recommend a logger with dependency injected logging capabilities. Not sure what’s out there in that regard. Feel free to re-use parts of G3log and create your own if that would be helpful - it’s public domain after all

**Comment by TelephonyMan** [comment]
That is because I ported my apps to g3log in windows first. There, each dll required g3log initialization when they are loaded dynamically. When compiled and run under Debian, only the first .so would successfully initialize. The second .so file when loaded would crash the process. It does say it is crashing because of multiple instantiation. So, I am trying figure out a workaround, will report back if I find something that works.

**Comment by TelephonyMan** [comment]
Ah, good news. I managed to solve it. I linked g3log as a static library instead of shared library. Now I am able to create different log file for each application .so file. A single Linux process now has multiple instances of g3mon, writing to different log files.

**Comment by KjellKod** [comment]
Very cool. I’ve no idea how you did that. 

Since other people have asked the same question can you post your changes or URL to your fork+branch?

**Comment by TelephonyMan** [comment]
Oh, I didn't change g3log code. I merely changed the CMake build file to create static library libg3logger.a file.

**Comment by TelephonyMan** [comment]
When multiple instances of g3log are running within the process, I wanted to know which log file will report the crash when it happens. So I injected some code that will cause a crash into one of my apps (.so file). When it crashed, the FATAL signal was not reported in that app log. It was reported in the log file of the app I loaded last. That makes perfect sense. The SIGSEGV handler for the process will always be with the last module that registered the signal handler.
