### ISSUE TITLE
Hide priority levels in g2 namespace or give them G2 specific names.

### ISSUE THREAD

**Issue by will2142** [KjellKod/g3log#21]
Since you're trying to make logger more useful for the general public, here is one suggestion base on a change I've had to make to use your library. 

Use slightly less generic names for the priority levels, especially since they're in the global namespace and can easily collide with names from other code.

This could be accomplished by just putting those levels in the g2 namespace, or prefixing them with G2.  (e.g. G2INFO, G2DEBUG).  

This is partially addressed with CHANGE_G3LOG_DEBUG_TO_DBUG.  but I think the namespace or G2 prefix would be a clearer solution.

P.S. Also, maybe change all the g2 references to g3?

**Comment by KjellKod** [comment]
I haven't precisely solved this yet. I have however added the possibility to, at initialization, add custom logging levels.  The standard ones are still there but now you can add both your non-fatal level as well as fatal level. 

From what I have heard only DEBUG has caused issues, which should be taken care of with DBUG. 

I am hesistant in changing the levels to G3DEBUG, G3INFO, G3WARNING ... etc due to that would have lots of consequences for coders out there. 

If INFO, WARNING, FATAL etc causes issues I hope people will tell me about it and I might reconsider. 

Sounds good Will?

**Comment by will2142** [comment]
Yeah, it's not an essential change, and it's easy enough to just change those level names yourself if necessary.
