### ISSUE TITLE
Architecture overview question

### ISSUE THREAD

**Issue by cowo78** [KjellKod/g3log#220]
Hello
as far as I understand (and please correct me) the LOG(F) macros basically:
1. Create a LogCapture instance to store file/line/level
2. call vsnprintf on a stack buffer to format the data (for LOGF) and/or use the ostringstream insertion operators
3. LogCapture destructor copies (to support shared objects allocated stuff) and forwards the input to a new heap LogMessage instance which manages sinks

Based on these points and reading your blog post it seems to me that the project is not well suited for an embedded realtime project for which the max latency should be ~5ms.
Things that come to mind (no particular order) are:
-. the formatting is done in the caller thread
-. heap allocations (architecture choice to support dlopen objects)
-. lock-based dynamic queue (architecture choice, see blog post)
-. synchronous file writes (new sink needed)
-. could benefit from faster formatting routines (i.e. http://fmtlib.net)

Am I missing something? Do you think it would make sense to make quite a few changes or will I hit some architecture choices? Of course features and stability are quite and interesting package and I would be hesitant to start over another project.

Would love to hear an expert comments.

Thanks

**Comment by KjellKod** [comment]
Hi,

I think you got that pretty good.
If you really have "hard realtime" and not "soft realtime" requirements
then please know that *no asynchronous *logger out there will likely meet
absolute on-paper calculated deadlines.
-- What is the "max latency" for?
a) If it is for "*max time for caller to make a LOG cal*l" then you would
be hard pressed  to find a scenario (or running on a very slow CPU
architecture) to see that ever be even near 5ms.
b) if the "max latency" is for "*from logging call, until it is written to
disk*" then I think you should rethink how your software operates because
that seems like a bad criterion.



One assumption you mentioned is not correct. The one for dlopen. If you
think about it (as you mentioned) there is a copy of the log message. I.e.
the calling instance will allocate on the heap but across the library
boundary a new heap allocation is made.

It is done that way especially for situations with dlopen in mind. There is
also a test example that exactly shows this :
https://github.com/KjellKod/g3log/blob/master/test_unit/test_linux_dynamic_loaded_sharedlib.cpp


??: I don't know what you mean with "synchronous file writes (new sink
needed)"
** The whole purpose of having an async logger is to avoid the "calling
thread I/O delay"  that which is a *huge* disadvantage for synchronous or
pseudo-synchronous loggers. Soft-realtime or not. If you are after a
synchronous logger I think you should think (*and rethink*) about the
reasons why you want that.



*Improvements in g3log and possibly (when that is started g4log) could
absolutely be: *- all string manipulation (similar to
http://fmtlib.net/latest/index.html) could be done in the background thread
**  currently however the final "log formatting" is not done in the calling
thread. It is done in the background sink thread but it is accurate that
the string operator "<<" or the sprintf calls does string+variable string
formatting in the calling thead.

- choice of queues lock-based dynamic as it is now vs compile time choice
of lock-free static size, or lock-free dynamic size with max size polizy (B)
**  As it stands now I'd choose (B) as that has shown very promising test
results with not so much of the bad side effects that other lock-free async
loggers has shown.

I hope I managed to answer some of the questions.  Feel free to continue to
ask here or you can also reach me at my personal email
Hedstrom at KjellKod dot cc

Thanks

* Contact Information
* Kjell Hedström
* Mobile:  +1 - 617.378.1915
* E-mail: Hedstrom@KjellKod.cc




On Fri, Jul 28, 2017 at 3:00 AM, Giuseppe Corbelli <notifications@github.com

**Comment by KjellKod** [comment]
Hi,

I think you got that pretty good.
If you really have "hard realtime" and not "soft realtime" requirements
then please know that *no asynchronous *logger out there will likely meet
absolute on-paper calculated deadlines.

**-- What calling sequence is the "max latency" targeting?**
1. a) If it is for "*max time for caller to make a LOG cal*l" then you would be hard pressed  to find a scenario (or running on a very slow CPU architecture) to see that ever be even near 5ms.
2.  if the "max latency" is for "*from logging call, until it is written to disk*" then I think you should rethink how your software operates because that seems like a bad criterion.

**One assumption you mentioned is not correct.** 
The one for dlopen. If you think about it (as you mentioned) there is a copy of the log message. I.e.
the calling instance will allocate on the heap but across the library boundary a new heap allocation is made.

It is done that way especially for situations with dlopen in mind. There is
also a test example that exactly shows this :
[test_unit/test_linux_dynamic_loaded_sharedlib.cpp](https://github.com/KjellKod/g3log/blob/master/test_unit/test_linux_dynamic_loaded_sharedlib.cpp)


**??**: 
I don't know what you mean with "synchronous file writes (new sink
needed)"

-  The whole purpose of having an async logger is to avoid the "calling
thread I/O delay"  that which is a **huge** disadvantage for synchronous or
pseudo-synchronous loggers. Soft-realtime or not. If you are after a
synchronous logger I think you should think (_and rethink_) about the
reasons why you want that.



**Improvements in g3log and possibly (when that is started g4log) could
absolutely be:**
1.  all string manipulation (similar to
http://fmtlib.net/latest/index.html) could be done in the background thread
**currently however** the final "log formatting" is not done in the calling
thread. It is done in the background sink thread but it is accurate that
the string operator "<<" or the sprintf calls does string+variable string
formatting in the calling thead.

2. choice of queues:  **lock-based dynamic** as it is now vs compile time choice
of:
**lock-free static size**, 
or **lock-free dynamic size with max size polizy** (B)
**As it stands now**  I'd choose (B) as that has shown very promising test
results with not so much of the bad side effects that other lock-free async
loggers has shown.

I hope I managed to answer some of the questions.  Feel free to continue to
ask here or you can also reach me at my personal email
Hedstrom at KjellKod dot cc

Thanks

**Comment by KjellKod** [comment]
closed due to inactivity
