### ISSUE TITLE
timestamp bug

### ISSUE THREAD

**Issue by xj-zhu** [KjellKod/g3log#227]
The timestamp processing section has bugs, such as the system inside the virtual machine. When the program is running, turning off the virtual machine without shutting down the virtual system will cause the system_clock and steady_clock differences to become unaligned. Similarly, resetting the system time will occur The same problem. (from Google translation)

**Comment by KjellKod** [comment]
That's an artifact of virtual systems and not a G3log bug. If it's a big issue then please bring it up with the virtual machine provider

**Comment by xj-zhu** [comment]
During the program run, reset the system time, the timestamp will go wrong. Whether on a virtual machine or on a physical machine.
The original example of the virtual machine is just a phenomenon, the actual reason as described above.
(From Google Translate)

**Comment by KjellKod** [comment]
Got it.

I think the reason why is the static storage of system to high granularity time conversion that was added in this PR

https://github.com/KjellKod/g3log/pull/200/files

See the function "time.hpp to_system_time"
Changing the system time is a fairly invasive operation and it's not uncommon that after doing this you have to restart processes due to similar issues.

I've called out the code in question. A simple change would be to remove the static but I believe (without having tested it) that it could have a performance penalty. 

I am not planning to address this. If you find a way that doesn't negatively affect performance  then please send a pull request for review. 

An option that doesn't require changing the code would be to restart your process after changing the system time

**Comment by xj-zhu** [comment]
In my project, the to_system_time function returns system_clock :: now () directly, although the precision is not the best, but the resolution of 0.1 microseconds is already high enough. Remove the static variable declaration and difference calculation that caused the bug.
