### ISSUE TITLE
Can I change config file at runtime and redirect log to a remote machine ?

### ISSUE THREAD

**Issue by RenathoAzevedo** [KjellKod/g3log#247]

**Comment by KjellKod** [comment]
There is no config file that g3log reads from.  You could redirect logs at runtime with a config file or with similar means in the following way. 

1. Read the config file with your own code. 
2. Use your own sink instead of the default sink or one of the sinks at https://github.com/KjellKod/g3sinks
(adding a sink is as easy or as hard as you want it to be... see the documentation)
3. Either use function calls to your sink (see documentation) to trigger changes based on `your code's logic for detecting and acting on config changes` or have your custom sink do this. 

G3log was made to be customizable. Allowing *any* API call to any sink made by users. 
It is not made with a ton of functionality such as remote logging. 

If you make a good logging sink, remote or not I recommend adding it to https://github.com/KjellKod/g3sinks for other users to enjoy.

**Comment by KjellKod** [comment]
Closing it since it's either a request for code changes (please add the PR) or a question for non-existing functionality (without plan to add a PR)
