### ISSUE TITLE
usage question - multiple log levels simultaneously

### ISSUE THREAD

**Issue by omerbrandis** [KjellKod/g3log#263]
hi,

this is a product/feature usage question,
( I was not able to infer an answer to this from the docs)

can i use g3log such that different objects and/or threads in my app, 
have different log levels (their log levels can be set/get individually at runtime) and write to different log files?

for example 
myclass    obj1,obj2.
obj1.set log level = logall;
obj2.set log level = lognone
obj1.log(ERROR,"text") -> will be written to file
obj2.log(ERRPR,"text") -> will be ignored.

thanks
Omer.

**Comment by KjellKod** [comment]
You can but it’s not designed with that in mind so you might get a performance hit depending on how you do it

I’ve described it below:
First however:
I understand the use case but I recommend
against it for the following reasons
1. You can already now have thread ID showing up in the log entry. If needed you could post process this to split to multiple files
2. All logs in one file gives a FIFO understanding of the system that split files won’t 
3. Logging should be sparse. Too much logging is a bad approach to design and troubleshoot your system and x -> file x, y-> file y can be an indicator of that anti pattern

——- howto —-

First: you can ad-hoc use whatever new logging levels you feel like using. You can have them defined per class or per object without any problems. See documentation and tests 

2nd two options: 
1. No performance hit
Take the default logging sink or the log rotating sink (see repo g3sinks) and modify it to your needs 
I.e have it write logging level X to file X
logging level Y to file Y etc

It should be fairly trivial to implement 
No real  disadvantage except that you have to implement the logic for “level x —> file x”

2: the other alternative would be to add as many sinks as you have need for. Each sink only deals with one file. Use g3sinks “log rotate and filter” sink to change it to be a whitelist instead of a blacklist approach
—-
I’ve used THIS approach for ONE extra file where Lua embedded code shoul log to its own log file. The g3sinks “filter and rotate” sink filtered out the default levels and only showed custom logging levels. The normal logging file showed all levels including custom ones. 
—-
Disadvantage is that all log entries would be sent to many sinks (where most entries are ignored unless they match whitelist)

**Comment by omerbrandis** [comment]
100%,

thank you very much,
Omer.
