### ISSUE TITLE
Exception handling question

### ISSUE THREAD

**Issue by cstamatopoulos** [KjellKod/g3log#306]
There is an external library that I was recently evaluating and I saw some strange behavior. I am not sure what is happening so I thought that maybe you could shed some light.
Said library seems to test CPU features which in failure raise exceptions. These exceptions are handled internally by the 3rd party library.

When g3log is initialized then my application crashes. I am able to replicate the same behavior by calling the function below after g3log is initialized.
```
bool testRaise()
{
	__try {
		RaiseException(
			EXCEPTION_PRIV_INSTRUCTION,                    // exception code 
			0,                    // continuable exception
			0, NULL);             // no arguments 
	}
	__except (GetExceptionCode() == EXCEPTION_PRIV_INSTRUCTION ?
		EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
	{
		return false;
	}

	return true;
}
```

If g3log is not initialized then the exception is caught inside testRaise() and program continues fine.
If g3log is initialized then the call stack is something like this
- vectorExceptionHandling is called 
- ReverseToOriginalFatalHandling();
- return exceptionHandling(p, "Vectored Exception Handler");
- return EXCEPTION_CONTINUE_SEARCH;

I would expect that after the last return, my exception would be handled inside testRaise() but instead the application crashes.

I should also add that I did read the comment in your code but I am not sure I understand 100%.
I guess what you are saying is that FATAL exceptions when caught inside g3log are only meant to be logged and that is it?
Even in the case of EXCEPTION_CONTINUE_EXECUTION it is still not handled but instead the app crashes.

**Comment by KjellKod** [comment]
Very Interesting - this is on Windows, right? 

If it’s a fatal exception then the correct handling is indeed to let the application crash. Anything else I would consider undefined behavior or a bug.

To clarify expected behavior: 
At installation G3log will store the previous exception handler. When a fatal exception happens (within the defined range of exceptions) the stackdump is sent with a fatal log entry. Once a fatal message is received the logger will flush all queued messages to the sinks and will then  shutdown the logging, the expected behavior is that the process will shut down thereafter. 

The `EXCEPTION_CONTINUE_SEARCH` is returned so that the default OS handler or another, previous, exception handler can be used. 

At this point. Once the logger has received a fatal event it cannot be used again. It is expected that the process should die at this point. 

Possibly you can re-initialize it but I haven’t tried this and it’s uncharted territory.  

—————-
I’m ASSUMING the following happens. 
1. G3log is initialized with fatal exception handling enabled
2. The fatal exception is raised.
3. The fatal exception is caught in g3log’s exception handling instead of the `testRaise` function. *I’m not sure about this but from your description that what it sounds like.*
4. Original fatal handling is restored. In case of G3log having a bug in the fatal log handling the original exception handler can deal with it. 
5. Fatal event is sent. Logging is shutdown. 
6. The fatal event continues. I.e the OS deals with the event and exits the process. 
7. I believe LOG calls can continue to happen but will be sent to cout instead. However I haven’t tested this on Windows but on Linux. 
—————
That said. I’ve added the option to disable G3log exception handling for the case where special handling of fatal exceptions are expected that goes outside of the G3log scope.  This seems like the option you want. 

——-
I should add that Windows exception handling is weird, poorly designed and confusing to understand. Some fatal handling have to be initialized per thread and other is global. 

It is absolutely possible I’ve screwed something up as I’m less familiar with Windows then Linux.

**Comment by cstamatopoulos** [comment]
I think you got everything right and thanks for explaining a few things.
I read the documentation on SEH to get a better understanding and I created a simple test case to see how the SEH handling works. 
What I still did not get is that why my exception inside testRaise() is not handled by my `__exccept` even though you specify `EXCEPTION_CONTINUE_SEARCH`.

When compared to what g3log does I found the cause is weird and is related to the StackWalk
```
      for (size_t index = 0; index < frame_pointers.size(); ++index)
      {
         if (StackWalk64(machine_type,
                         GetCurrentProcess(),
                         GetCurrentThread(),
                         &frame,
                         context,
                         NULL,
                         SymFunctionTableAccess64,
                         SymGetModuleBase64,
                         NULL)) {
            frame_pointers[index] = frame.AddrPC.Offset;
         } else {
            break;
         }
      }
```

For index >= 1 my exception handling inside testRaise() is working fine (along with my breakpoint even). For index == 2 the breakpoint does not seem to work but the function returns false so I guess it is OK. For anything > 3 I just get a crash.
I do not understand why but these are just my observations.

Of course as you said the log is shutdown after that anyway. I have not looked at re-initializing it yet.

**Comment by KjellKod** [comment]
If your other 3rd party library is handling the fatal exceptions then disabling the G3log fatal handling is an option. You can do that through the cmake config

**Comment by cstamatopoulos** [comment]
This all happens when the library is initialized where it checks what features the CPU support (this the Privileged Instruction exceptions). I can always initialize it before the logging, I just wanted to understand what exactly is going on.
