### ISSUE TITLE
log_prefix cannot contain parantheses

### ISSUE THREAD

**Issue by dtecta** [KjellKod/g3log#31]
In 

    auto logger = g3::LogWorker::createWithDefaultLogger(argv[0], myDir);

creation fails if argv[0] contains parentheses, for example as in

    "C:/Program Files (x86)/InstallDir/myApp.exe"

I currently do not have a fix. I work around this problem by not using argv[0] as prefix.

**Comment by KjellKod** [comment]
Thanks.

What's the error message when it exits?

**Comment by dtecta** [comment]
Program aborts before closing the log. The abort() is in filesink.cpp, line 25. Parentheses () are listed as illegal characters in filesinkhelper.ipp, line 27. I'm not sure about other OSes but parentheses are legal filename-characters under Windows.

**Comment by KjellKod** [comment]
It can certainly be removed from the illegal characters.  '(' and ')' can be used both on Windows and Linux. In general I think it is a bad habit to use these characters for file entity names since they have to be "escaped" when accessing them but yes, they are legal. 

You can either do a pull request or wait for me to get to fix it.  The fastest option is to do a pull request since  I'm heads down with other work so I won't get to it myself for a few weeks.

**Comment by KjellKod** [comment]
fixed in https://github.com/KjellKod/g3log/pull/81/files?w=1
