### ISSUE TITLE
Is custom sink thread safe?

### ISSUE THREAD

**Issue by ZhihaoGong** [KjellKod/g3log#323]
I added a custom sink to log messages to stdout. Is calling a custom sink thread safe? or I need to handle that on myself? Thanks.

**Comment by KjellKod** [comment]
If you call it with the APIs provided in g3log (LOG etc + calling other functions to the sink through the sink handle) that should be thread safe. It’s made that way by design. The calls are routed through thread safe queues between the threads 

There are plenty of examples in the docs and unit tests that you can check

**Comment by KjellKod** [comment]
You can check the repo g3sinks for a sink that color codes the logs and puts them to stdout

**Comment by ZhihaoGong** [comment]
thanks!
