### ISSUE TITLE
Can't compile in MSVC 2019 with /std:c++latest 

### ISSUE THREAD

**Issue by ripopov** [KjellKod/g3log#351]
vcpkg\installed\x64-windows\include\g3log/future.hpp(45): error C2039: 'result_of': is not a member of 'std'

Looks like result_of was removed in C++20:
https://en.cppreference.com/w/cpp/types/result_of

**Comment by KjellKod** [comment]
G3log supports C++14, C++17 but not yet C++20

**Comment by HJLebbink** [comment]
We have been using g3log for several years and we would like to do so for many to come. But some are having uneasy feelings this important component is currently preventing c++20 compatibility tests. I have also have looked at this issue, and whether it could be resolved in a day or so. Sadly, the answer is likely not, because of the impact it may have on concurrency and IO. I guess anybody needs to have such changes tested thoroughly. 

**Question**: @KjellKod can you say anything about c++20 support somewhere. I know that building os software can be pain in the $ss, thus, the answers: "not in 2020" and "please do it yourself" are understandable.

regards HJ

**Comment by KjellKod** [comment]
At this point, g3log does not support c++20.  Moving from C++14/17 to C++20
is a breaking change (unless I want to keep a bunch of ifdefs in the code)
The changes are fairly trivial and involve like you called out some
concurrency changes in regard to packed tasks and futures. The changes are
well specified and contained.

At this point, I have not planned to take on this work in 2020 but nothing
is *really* stopping me or the community to take it on.

Since a while back I mostly rely on the community to drive the changes in
g3log. I am happy to provide guidance, support and review PRs that would
address the move to C++20.
For company critical support - such as upgrading g3log to support C++20
within a given timeframe - driven by me, not by the community - I would ask
that to be handled on a contract basis. You can reach me on my private
email (ref my github page) if that is of interest.
