### ISSUE TITLE
Use std::signal to install signal handler instead of the c-way 

### ISSUE THREAD

**Issue by craig-cogdill** [KjellKod/g3log#39]
Ref: crash handler
http://en.cppreference.com/w/cpp/utility/program/raise

**Comment by AlphaCluster** [comment]
You're talking just on the unix crash handler correct? I can actually make a fix for this.

**Comment by KjellKod** [comment]
I have to read up. Unless C++14?has changed the standard I do believe sigaction is better
Reg: http://stackoverflow.com/questions/231912/what-is-the-difference-between-sigaction-and-signal

**Comment by AlphaCluster** [comment]
I think your right. I don't believe C++14 has anything along those lines. Also looking the gnu C++ std lib which just forwards signal to glibc I would agree explicitly calling sigaction seems safer since even though one guy in that stack overflow claims it's being called I couldn't find that to be the case.

**Comment by KjellKod** [comment]
No action right now.   The good thing is that reading up on this made me realize of fatal signal handling could be improved on Clang.  The work to continue to improve this on nix and windows continues ... :smile:
