### ISSUE TITLE
Please, provide std::filesystem::path overloads for FileSink

### ISSUE THREAD

**Issue by DlubalSmidJaroslav** [KjellKod/g3log#429]
**Is your feature request related to a problem? Please describe.**
I have issue on Windows, where user has Unicode characters in his profile directory. It is Chinese name on English version of Windows. Application using this library is using C locale for compatibility reasons and even if we used system-default locale (english), this path couldn't be converted to system-default multibyte encoding.
The only way to pass such path for me to this library is to link to universal CRT (UCRT), temporarily change global locale to utf8 locale, create the FileSink with path converted to UTF-8, and then switch back to previous locale (using windows-specific per-thread locale change function).

**Describe the solution you'd like**
Providing std::filesystem::path overloads would be good solution. I see the requirement for this library in master branch is C++17, filesystem should be available there. I don't know where non-MSVC compilers are with support. If that would be an issue, maybe providing wstring overloads (and using MSVC-specific ofstream constructor) would suffice.

**Comment by KjellKod** [comment]
g3log is community driven. Due to other priorities in my life I am not planning to drive feature changes myself but can collaborate, review and help community contributors.  Changes to existing code must be backwards compatible. Frequently changes can be made by extending through sinks instead. I.e. github.com/KjellKod/g3sinks. 

For additional context and possible help you can also see this issue that @AndreasSchoenle worked with: https://github.com/KjellKod/g3log/issues/123

**Comment by ArosPrince** [comment]
This is also related: #415 

Since your app is Windows, if this is a single user environment, you may want to consider moving your log location to `%ProgramData%`. Or even if there are multiple users and you don't mind having all the logs on one heap. Or you could use WinAPI `GetSecurityInfo` to distinguish which log is for which Windows user.

**Comment by KjellKod** [comment]
Thanks @ArosPrince . Loved the context and for providing a workaround that requires configuration changes rather than spinning up a new sink. I'll go ahead and close this ticket. 

If @DlubalSmidJaroslav considers solving this through a PR here or to https://github.com/KjellKod/g3sinks then I'll happily review it or provide in-process collaboration.
