### ISSUE TITLE
How to customize how g3log reacts to fatal 

### ISSUE THREAD

**Issue by HarryDC** [KjellKod/g3log#431]
### Uncertain what's going on? Do you need advice or help troubleshooting?
We are currently using g3log in iMSTK (https://www.imstk.org/) and are using `CHECK` to enforce contracts, which is fine for running applications standalone, atm we are in the process of creating a Wrapper that enables us to use imstk through Unity. Swig is used to generate C# bindings. The issue is that whenever we run into a CHECK that fails the ensuing `abort()` will take crash unity in a way that sometimes need Process Explorer to kill the process before it can be started again 

### Describe the solution you'd like
Is there a way to prevent `abort()` from being called when CHECK fails or a log(FATAL) occurs ? for example could we throw an exception or deal with the error in another way ?

**Comment by KjellKod** [comment]
@HarryDC there are a couple of things that is good to know as they might help you out. 

1. The fatal handling is taken care of in g3log::saveMessage ([link to function](https://github.com/KjellKod/g3log/blob/a7192f2b1c921f5b12dac72c9ee4ddc6abb89287/src/g3log.cpp#L158))
2. saveMessage calls a function pointer that does the fatal handling. By default that function will make sure that the proper steps are taken to capture the message, getting it to the log before the process is forced to exit. 
Please see [pushFatalMessageToLogger](https://github.com/KjellKod/g3log/blob/a7192f2b1c921f5b12dac72c9ee4ddc6abb89287/src/g3log.cpp#L228) for how it works by default.  
3. that `function pointer` that deals with the fatal message **can be overridden**. There are several clients who has done this AFAIK as they want to provide their own fatal handling rather than relying on g3log's mechanism.   Please see 
4. Examples of this overriding can be found in unit testing: [helper class](   RestoreFileLogger::RestoreFileLogger(std::string directory)), example of unit test [[1](https://github.com/KjellKod/g3log/blob/9bb36eb7e5d86a1355d36a7506ea169de88d06b8/test_unit/test_io.cpp#L549)] and [[2](https://github.com/KjellKod/g3log/blob/9bb36eb7e5d86a1355d36a7506ea169de88d06b8/test_unit/test_io.cpp#L835)] test_io.cpp has several examples of this. 
5. A whole other potential solution could be to override the signal handler and still relying on the general approach for g3log's fatal error handling. 


If you choose to override the `function pointer`, keep in mind that this override and g3log initialization should happen before threads are started, as synchronizing otherwise the global function pointer with thread is outside the scope of current g3log functionality. 

At least one company that overrode this fatal handling pretty much followed exactly how g3log does it, they just added additional steps that were needed for them.  (for additional work there's also a "pre-fatal" step that can be overridden, check the code or ask if that's of interest)

**Comment by HarryDC** [comment]
Thanks, we will give this a shot !
