### ISSUE TITLE
Latest release 1.3.4 does not support C++20

### ISSUE THREAD

**Issue by morph208** [KjellKod/g3log#465]
Hello,

The latest release does not compile with C++20. It has been fixed in the master for almost 2 years now (see https://github.com/KjellKod/g3log/pull/392). Are you planning to create a release with this support? I am asking because we are using g3log in our software and we work in a regulated environment. We need to have full traceability in the pieces of software we use. And it is difficult to use the master at a given date. A defined version would be much preferred.

**Comment by KjellKod** [comment]
Thanks for letting me know. COVID years put a wrench in so many things, including keeping track of g3log releases. I can absolutely do that. I'll create a release with g3log and g3sinks that is based on master and with the full description of the changes since [1.3.4](https://github.com/KjellKod/g3log/tree/1.3.4). It should be out before Monday, Nov 7th.

**Comment by KjellKod** [comment]
Resolved with: https://github.com/KjellKod/g3log/releases/tag/2.0.1 and https://github.com/KjellKod/g3sinks/releases/tag/2.0.2
