### ISSUE TITLE
[Question] Different levels for different domain

### ISSUE THREAD

**Issue by clauderobi** [KjellKod/g3log#466]
HI,

I am trying to figure what would be the best strategy to support having different level for different domains. For example, lets says I want to debug networking things in my code I would want to set a lower level but just the log entries corresponding to my networking stack. 

Using different log system instance would work but I understand that this is not supported.

Another method is to use different specialized sink(s) and use the LEVEL space by allocating different ranges to different domains. This would work but appears to be a kludge. 

But is there another strategy / feature that I am not aware of?

**Comment by KjellKod** [comment]
`Using different log system instance would work but I understand that this is not supported.` 
Correct. If you want to use the global access point for logging that wouldn't be a feature that g3log supports. 
You could also use a local instance that talks with a sink. It's kind of hacky but wouldn't be that complex to swing.

**Comment by KjellKod** [comment]
LOG_IF or dynamically turning on/off message level might be your best bet if you want to handle it at the msg source origin. FYI: unless you are hammering the sinks with lots of noisy messages then the overhead for dealing with it at the log sink level isn’t that high.  A code copied sink that you adjust for your purposes, and you can thread-safe call the sink through the sink-handle (check docs and unit tests) is a very flexible solution. Unless logging is extreme that’s still the solution I’d recommend. On Nov 17, 2022, at 6:46 AM, clauderobi ***@***.***> wrote:﻿
Thanks Kjell,
The LogRotateWithFilter is what I had in mind as a workaround.

I guess I was not clear as to what I am trying to do. Lets put a simple case;
void someNetworkFunction() {
...
LOG(G3LOG_DEBUG) << "Some network error message";
LOG(INFO) << "Network info";
}
...
void someFIleSystemAccessFunction() {
LOG(G3LOG_DEBUG) << "Some file access error message";
LOG(INFO) << "File access info":
}
I want to be able to say (or any other different combination, based on some system configuration)
g3::log_levels::setHighest(G3LOG_DEBUG) for network
g3::log_levels::setHighest(INFO) for file system access
While writing this message I found the LOG_IF macro. Using it is a third alternative to achieve what I need; I would create a small configurable library to provides some static methods to feed the LOG_IF macro.
Ultimately, another way of saying what I am trying to do is I am looking for a way to control levels at the message source rather than message sink. The actual implementation should be in some form in the library. An example is the LOG_IF macro.
On the long run, may be having a solution modeled like the base / derive exception class where the level space is not just linear but hierarchical (or parent / child, or base / derived) would be a great addition. Each node in the graph could then have its own optional level threshold. The python logging library has something along those lines (handlers + loggers). But it is limited.

**Comment by clauderobi** [comment]
Here is what I did. It is not that long long so I am posting it here.

in an include file I have this

namespace g3 {
`  class domainLevels;
  typedef std::string                           DOMAINS;
  typedef std::shared_ptr<domainLevels>         domainLevels_p;
  typedef std::unordered_map<DOMAINS, LEVELS>   domainList_t;

  const std::string                             SEPARATOR = "::";
  const DOMAINS                                 NEDOMAIN = "";
  extern domainLevels_p                         domainManager;

  class domainLevels {
  public:
    // We will be constucted during process init so we should not be doing memory stuff....
    domainLevels() { };

    static domainLevels_p                       instance();

    static DOMAINS                              insertDomain(const DOMAINS& d) { instance()->insert(d); return d; };
    static bool                                 evaluateLevel(const LEVELS& l, const DOMAINS& d) { return instance()->evaluate(l, d); };

    void                                        setLevel(const LEVELS& l, const DOMAINS& d) { if (domainList.insert({d, l}).second == true) return; domainList.at(d) = l; };

    void                                        printInfo() const;
  private:
    void                                        insert(const DOMAINS& d) { setLevel(FATAL, d); };
    bool                                        evaluate(const LEVELS& l, const DOMAINS& d);

    domainList_t                                domainList;
  };

  #define ADDDOMAIN(domain)  g3::DOMAINS v = std::string(NEDOMAIN + SEPARATOR + domain); const g3::DOMAINS NEDOMAIN = domainLevels::insertDomain(v)
  #define NELOG(lvl) LOG_IF(lvl, domainLevels::evaluateLevel(lvl, NEDOMAIN))`
}

the implementation for the methods is

`namespace g3 {

  domainLevels_p                     domainManager = nullptr;

  domainLevels_p domainLevels::instance() {
    if (domainManager == nullptr) {
      domainManager = std::make_shared<domainLevels>();
    }
    return domainManager;
  }

  bool domainLevels::evaluate(const LEVELS& l, const DOMAINS& d) {
    DOMAINS     current = d;
    while (current != NEDOMAIN) {
      try {
        LEVELS  lvl = domainList.at(current);
        if (l.value >= lvl.value) {
          // Enabled at this level
          return true;
        }
      } catch(...) {}

      // Move up to parent - Remove the last segment
      std::size_t     pos = current.rfind(SEPARATOR);
      if (pos != std::string::npos) {
        current.erase(pos);
      } else {
        // Not found, we will end up with an empty current domain indicator
        break;
      }

    }

    // Top level
    try {
      return (l.value >= domainList.at(NEDOMAIN).value);
    } catch (...) {
      domainList.insert({NEDOMAIN, FATAL});
      return (l.value >= domainList.at(NEDOMAIN).value);
    }
  }

  void domainLevels::printInfo() const {
    std::cout << "**** Configured domains" << std::endl;
    for (const auto& domain : domainList) {
      std::cout << "\tDefined level for domain " << domain.first << " is " << domain.second.text << std::endl;
    }
  }


}`


I am using namespace all over my code so in namespaces I want to control individually, I simply need to add
ADDDOMAIN("test") ;  // This adds domain test under the current domain ( resulting in ::test for a top level namespace) 
and then to set a threshold only valid in the namespace I simply have to do this:
g3::domainLevels::instance()->setLevel(INFO, NEDOMAIN); 

Nested namespaces work well too.

If interested I could create a pull request if you tell in which repository

**Comment by KjellKod** [comment]
[g3sinks](https://github.com/KjellKod/g3sinks) would be the place. 
- Update the readme to either describe is quickly, or point to a README in your created folder (i.e. `domain_logger` (or whatever)). 
- Setup a minimalistic CMake file or possibly even just compilation and run instructions
- Any unit tests that can be added are highly recommended

You can see other examples in g3sink on how to set them up.

**Comment by KjellKod** [comment]
even if it's just a `<snipped>`and not a library.. you can see how we created other snippets and it would likely still be valuable to other community members if it's given some README love.

**Comment by KjellKod** [comment]
it seems either @clauderobi  got what was needed

**Comment by clauderobi** [comment]
Yes indeed.

I'd like to contribute back but I am struggling at making the solution 100% usable.... My solution is centered around a new LOG macro (different name) that relies on a per namespace variable to select a different threshold. In theory all is good. However:
1 - If the variable is not defined in a given namespace, the compiler will complain of multiple definitions (because other namespaces do have a definition). In other words, at the macro level, I did not find a way to provide a default value.
2 - Support for the case where a namespace is defined with multiple include files needs an automatic solution. Right now I just manually make sure that the variable is defined once. 

1 is really problematic.  For 2, a solution is probably possible.
