### ISSUE TITLE
[Question] how to know if the logger was initialized

### ISSUE THREAD

**Issue by Dredok** [KjellKod/g3log#484]
### Uncertain what's going on? Do you need advice or help troubleshooting?
When working with a library, you can not be sure if the logging was initialized by other library or the main executable. One solution would be to delegate that responsability to the library caller, but then the library caller should be sure that no one else has already initialized it (ie. a different library for example ...)

### Describe the solution you'd like
Just make visible/public the `internal::isLoggingInitialized()` 
https://github.com/KjellKod/g3log/blob/master/src/g3log.cpp#L121

### Describe alternatives you've considered
as a workaround without modifying the library, I have to make a cumbersome singleton which everyone should use and even then its not enough to guarantee that no other libraries have instantiated the g3log on its own.

**Comment by KjellKod** [comment]
internal::isLoggingInitialized()Is already public. Nothing prevents you from calling it The reason why it isn’t public is because calling it means the coder is likely straying from the g3log’s recommended approach of initializing it. There might be special reasons why you still need to do this and for that reason you can call it. It’s not protected against startup race conditions nor - which are handled by the recommended initialization steps instead. If you want to call it, just use the full pathg3::internal::isLoggingInitialized()Sent from my iPhoneOn Mar 24, 2023, at 6:29 AM, Dredok ***@***.***> wrote:﻿
Uncertain what's going on? Do you need advice or help troubleshooting?
When working with a library, you can not be sure if the logging was initialized by other library or the main executable. One solution would be to delegate that responsability to the library caller, but then the library caller should be sure that no one else has already initialized it (ie. a different library for example ...)
Describe the solution you'd like
Just make visible/public the internal::isLoggingInitialized()
https://github.com/KjellKod/g3log/blob/master/src/g3log.cpp#L121
Describe alternatives you've considered
as a workaround without modifying the library, I have to make a cumbersome singleton which everyone should use and even then its not enough to guarantee that no other libraries have instantiated the g3log on its own.
Additional context
