### ISSUE TITLE
[Question] Have modules from the app log only to certain sinks (not in all sinks)

### ISSUE THREAD

**Issue by IDaniel99** [KjellKod/g3log#533]
I have a c++ application that has different modules ( Class A, Class B etc). I want to have sinks specific to each module. For example in class A and class B if I log something it should go to a global file but also to a private file specific to module A and another one specific to module B.
I created a wrapper class around g3log, but if I add a sink all logs go to that sink.

There was a similar question some time ago: https://github.com/KjellKod/g3log/issues/153

Initially I wanted to have different workers for different modules, but it gives error for duplicate initialisation, now I want to use the sinks to achieve this functionality, any ideas?

**Comment by KjellKod** [comment]
I think that question discussed it at lenght. 

g3log is not designed with that primary use case. That said, it can still be done. If I had to do it and really wanted to use g3log then I'd probably do something like this. 

Use a custom sink, possibly just editing or borrowing lots of thinking from g3sinks filtering sink https://github.com/KjellKod/g3sinks . 

For this custom sink I'd either follow a generic schema so that class or file logs gets saved to their own dedicated file. 
OR I would have it so I can [call](https://github.com/KjellKod/g3log/blob/master/docs/API.md#g3log-and-sink-usage-code-example) the sink and decide that file a.....x would belong to "moduleA" and y....z belong to moduleZ etc and each file group would be saved to a dedicated file. 

I.e. you would have to write your own sink logic but you could utilize the existing g3log framework without trying to **hack** it. G3log was made to allow for super easy extention of sinks. Check the examples, unit tests and g3sinks for insights.

**Comment by KjellKod** [comment]
Another way to do it is post-processing. 

Allow g3log to run it's course and then you use log filtering and just parse the log into whatever other file view that is of interest. This is more dynamic since you can adjust that more easily than you can go back in time and change how you implemented sinks. 

python, c++, javascript, rust, lua, go, linux command tools awk/sed/grep all excellent utilities that can use the class, function and file information to create what you need.
