### ISSUE TITLE
Multiple worker creation is legal

### ISSUE THREAD

**Issue by rakeshsehgal1** [KjellKod/g3log#93]
Hello

I have been using G3log for my project. Really good job, the code is really beautiful (the way you got things done). Just wanted to know the use case of the worker thread. Reading through your code I thought the Worker thread is supposed to be singleton, as the otherwise doesn't make sense to me (multiple worker writing to sink?). I could do the following and observed 5 thread: (main + 2 + 2)

int main()
{
        std::unique_ptr<LogWorker> logworker {LogWorker::createLogWorker()};
        std::unique_ptr<LogWorker> logworker1 {LogWorker::createLogWorker()};
        auto sinkHandle = logworker->addSink(std2::make_unique<MySink>(), &MySink::SendMessageToMySink);
       auto sinkHandle2 = logworker->addSink(std2::make_unique<MySink>(), &MySink::SendMessageToMySink);

      initializeLogging(logworker.get());
      initializeLogging(logworker.get());
}

Maybe you are missing the std::once before doing new LogWorker? Would really appreciate some light on this.

Thanks
-R

**Comment by KjellKod** [comment]
Did you really call initialize logging twice?

 
There is a CHECK in g3log.cpp so that if you call initialize logging multiple times there's a FATAL exit.
CHECK(!internal::isLoggingInitialized()); 

Apart from that, yes you can have as many sinks as you want. You can also have as many background workers as you want, but only one can be used to dispatch the LOG calls (the one that is initialized). Only the sinks that are attached to active "ref: initializeLogging(...)" will see the LOG calls.  

The background worker has a log message dispatching thread that it sends to the sinks. Each sink is powered by its own Active object (no CPU used unless there is work to do).


--- 

There are reasons why you might want to use a sink by itself. For example doing some custom logging outsides of the g3log API of scope. However in that case it is likely better to use `Concurrent<T>` instead of g3::LogWorker (ref: https://github.com/KjellKod/concurrent)

**Comment by KjellKod** [comment]
I confirmed that there was a initialization/shutdown bug if initializeLogging was called multiple times. At some point a while back the CHECK(...) call in the initialization triggered a deadlock instead of a fatal exit. 

I have changed that in https://github.com/KjellKod/g3log/pull/94

**Comment by KjellKod** [comment]
The only issue here was the deadlock that could happen when calling ```initializeLogging(...)``` twice. 
That was resolved in https://github.com/KjellKod/g3log/pull/94

**Comment by rakeshsehgal1** [comment]
Thanks for the explanation! :)
